### ISSUE TITLE
Rendering View HTML with CSV::fromArray($array)->render()

### ISSUE THREAD

**Issue by affinitycloud** [mnshankar/csv#13]
Hi,

When using CSV::fromArray($array)->render() it appears to be outputting view HTML at the end of the CSV. Is this a bug? Cheers.

**Comment by mnshankar** [comment]
Hi,
Please share your code so I can troubleshoot more effectively. The following snippet (Laravel) works as expected for me:

```php
Route::get('test', function(){
    $arr = array(
        array('name'=>'name1', 'address'=>'address1'),
        array('name'=>'name2', 'address'=>'address2'),
    );
    return CSV::fromArray($arr)->render();
});
```

**Comment by borislavgit** [comment]
This is happening only on Safari and only in specific cases.

I have multiple arrays and 3/4 are downloaded as csv files, only one is downloaded as a html.

Though this is not fatal since the information is still there, it's kind of confusing as to why is that happening.

**Comment by jamesfairhurst** [comment]
Happening for me too in Chrome, still using 4.1.* unfortunately.

Adding an exit fixes it:

```
public function render($filename = 'export.csv', $mode = 'r+')
    {
        header('Content-Type: text/csv');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Cache-Control: private');
        header('pragma: cache');

        //$this->handle = fopen('php://output', $mode);
        echo $this->toString();exit;
    }
```

So not sure where Laravel is adding the HTML.

**Comment by affinitycloud** [comment]
These are the functions I'm using to render the CSV:

    public function exportOpens($id)
    {
        $opens = MailchimpWrapper::reports()->opened($id);
        $export = $this->mapOpensForExport($opens);

        return CSV::fromArray($export)->render();
    }

    public function mapOpensForExport($opens)
    {
        foreach ($opens['data'] as $subscriber) {
            $subscribers[] = [
                'Email' => $subscriber['member']['merges']['EMAIL'],
                'First Name' => $subscriber['member']['merges']['FNAME'],
                'Last Name' => $subscriber['member']['merges']['LNAME']
            ];
        }

        return $subscribers;
    }

It renders a CSV for download but right at the bottom of the CSV it adds the HTML for my admin layout blade file.

**Comment by mnshankar** [comment]
Hi,
Unfortunately, I am still unable to replicate the issue at my end.
Can you please see if adding an fclose($this->handle); just before return
ob_get_clean() in function toString() fixes it?

Thanks!

**Comment by Yavor-Ivanov** [comment]
Hello, I'm experiencing the same problem with one of my csv exports. I tried adding `fclose($this->handle);` to the toString method, but then I get a `Serialization of 'Closure' is not allowed` exception. The file outputs fine if I add an `exit;` to the `render` method like @jamesfairhurst suggested. Here's the log:
```
[2015-08-17 12:48:34] dev.ERROR: exception 'ErrorException' with message 'fclose(): 462 is not a valid stream resource' in /var/www/labworm/vendor/mnshankar/csv/src/mnshankar/CSV/CSV.php:91
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'fclose(): 462 i...', '/var/www/labwor...', 91, Array)
#1 /var/www/labworm/vendor/mnshankar/csv/src/mnshankar/CSV/CSV.php(91): fclose(Resource id #462)
#2 /var/www/labworm/app/utils/CSVExporter.php(115): mnshankar\CSV\CSV->put('/var/www/labwor...')
#3 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Database/Connection.php(458): CSVExporter->{closure}(Object(Illuminate\Database\MySqlConnection))
#4 [internal function]: Illuminate\Database\Connection->transaction(Object(Closure))
#5 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(321): call_user_func_array(Array, Array)
#6 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#7 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\Database\DatabaseManager->transaction(Object(Closure))
#8 /var/www/labworm/app/utils/CSVExporter.php(116): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#9 /var/www/labworm/app/utils/CSVExporter.php(116): Illuminate\Support\Facades\DB::transaction(Object(Closure))
#10 /var/www/labworm/app/commands/Export.php(42): CSVExporter->export(NULL)
#11 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): Export->fire()
#12 /var/www/labworm/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\NullOutput))
#13 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\NullOutput))
#14 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Console/Application.php(101): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\NullOutput))
#15 [internal function]: Illuminate\Console\Application->call('export', Array)
#16 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Foundation/Artisan.php(57): call_user_func_array(Array, Array)
#17 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(211): Illuminate\Foundation\Artisan->__call('call', Array)
#18 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(211): Illuminate\Foundation\Artisan->call('export', Array)
#19 /var/www/labworm/app/controllers/CSVController.php(24): Illuminate\Support\Facades\Facade::__callStatic('call', Array)
#20 /var/www/labworm/app/controllers/CSVController.php(24): Illuminate\Support\Facades\Artisan::call('export', Array)
#21 [internal function]: CSVController->downloadCSV('website_traffic...')
#22 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#23 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('downloadCSV', Array)
#24 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(CSVController), Object(Illuminate\Routing\Route), 'downloadCSV')
#25 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CSVController', 'downloadCSV')
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('website_traffic...')
#27 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#28 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#29 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#30 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#31 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#32 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#33 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#34 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#35 /var/www/labworm/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#36 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#37 /var/www/labworm/public/index.php(49): Illuminate\Foundation\Application->run()
#38 {main} [] []
[2015-08-17 12:48:34] dev.ERROR: exception 'Exception' with message 'Serialization of 'Closure' is not allowed' in /var/www/labworm/vendor/laravel/framework/src/Illuminate/Session/Store.php:236
Stack trace:
#0 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Session/Store.php(236): serialize(Array)
#1 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(126): Illuminate\Session\Store->save()
#2 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(79): Illuminate\Session\Middleware->closeSession(Object(Illuminate\Session\Store))
#3 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#4 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#5 /var/www/labworm/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/labworm/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#7 /var/www/labworm/public/index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
```

**Comment by jamesfairhurst** [comment]
I could also fix it by setting an empty layout e.g.

`$this->layout = '';`

Think the ob stream buffer is picking up the HTML somehow or Laravel appending it after the CSV string has been created.

**Comment by mnshankar** [comment]
I added an exit as recommended by  @jamesfairhurst and @Yavor-Ivanov. Please use ver 1.8. Hopefully this issue is resolved.
